server:
  port: 8080

mybatis-plus:
  global-config:
    enable-sql-runner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启sql日志
    map-underscore-to-camel-case: true
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

canal:
  instance :
    host: 192.168.254.132
    port: 11111
  mq:
    topic: example
  deal:
    batchsize: 1000
  file:
    path: canal

ftp:
  host: 192.168.254.132
  port: 21
  username: tung
  password: tung
  encoding: GBK
  filepath: /opt/canal_sql_file/


send:
  enable : false
  synctype: ftp
  filesync:
    path: /canal/
    ftppath: /opt/canal_sql_file/

receive:
  enable : true
  monitorpath : /canal/
  intervaltime: 10
  filtersuffix : .sql

es:
  host: 192.168.254.132
  port: 9200
  indices: datatran