server:
  port: 8080

datatran:
  send:
    enable: true
  receive:
    enable: true

canal:
  instance :
    host: 192.168.254.132
    port: 11111
  mq:
    topic: example
  deal:
    batchsize: 1000
  file:
    path: canal

ftp:
  host: 192.168.254.132
  port: 21
  username: tung
  password: tung
  encoding: GBK
  filepath: /opt/canal_sql_file/